const VOCAB=[['sensitivity label','rótulo de confidencialidade'],['data classification','classificação de dados'],['data loss prevention','prevenção contra perda de dados'],['retention','retenção'],['data lifecycle','ciclo de vida dos dados'],['insider risk','risco interno'],['communication compliance','conformidade de comunicação'],['Activity Explorer','explorador de atividades'],['Data Explorer','explorador de dados'],['Compliance Manager','gerenciador de conformidade'],['Microsoft Graph','grafo de contexto e dados'],['grounding','fundamentação com contexto'],['oversharing','compartilhamento excessivo'],['DSPM for AI','gerenciamento da postura de dados para IA'],['content search','pesquisa de conteúdo'],['restricted access control','controle de acesso restrito']];
const Q=[
{topic:'Information Protection',q:'Which feature can classify content and apply protection that travels with a document?',o:['A retention policy','A sensitivity label','Content search','Communication Compliance'],c:1,n:'O rótulo de confidencialidade classifica e pode aplicar proteção persistente ao documento.'},
{topic:'Data Loss Prevention',q:'A company must prevent users from emailing credit card numbers outside the organization. What should it configure?',o:['eDiscovery','Data Explorer','Insider Risk Management','A DLP policy'],c:3,n:'DLP avalia o conteúdo e a ação para alertar, justificar ou bloquear o envio.'},
{topic:'Data Lifecycle',q:'Which solution determines how long business content must be kept and when it can be deleted?',o:['Data Lifecycle Management','Defender XDR','Activity Explorer','Microsoft Graph'],c:0,n:'Data Lifecycle Management usa controles de retenção e descarte.'},
{topic:'Copilot data access',q:'What primarily determines which organizational content Microsoft 365 Copilot can use for a user?',o:['The user’s job title','A global Copilot data store','The user’s existing permissions','The prompt length'],c:2,n:'O Copilot usa conteúdo que a identidade já tem permissão para acessar.'},
{topic:'Risk investigation',q:'Which solution correlates signals to identify potentially risky activity by users inside an organization?',o:['Communication Compliance','Insider Risk Management','Compliance Manager','Content search'],c:1,n:'Insider Risk Management é focado em possíveis riscos internos.'},
{topic:'Activity Explorer',q:'An administrator must review actions taken on labeled content. Which tool should be used?',o:['Activity Explorer','Data Explorer','eDiscovery','SharePoint admin center'],c:0,n:'Activity Explorer mostra eventos e atividades executadas sobre o conteúdo.'},
{topic:'DSPM for AI',q:'Which Microsoft Purview capability provides visibility into data security risks related to AI use?',o:['Retention labels','DLP alerts','Communication Compliance','DSPM for AI'],c:3,n:'DSPM for AI ajuda a descobrir uso de IA e avaliar a postura de segurança dos dados.'},
{topic:'eDiscovery',q:'A legal team needs to preserve, collect, and review content for an investigation. What should it use?',o:['Restricted access control','Compliance Manager','eDiscovery','A sensitivity label'],c:2,n:'eDiscovery gerencia casos e evidências; pesquisa é uma parte possível do fluxo.'},
{topic:'SharePoint oversharing',q:'Which report helps administrators identify sites and content that may be exposed too broadly?',o:['A data access governance report','A message trace','A billing report','A sign-in log'],c:0,n:'Relatórios de governança de acesso a dados ajudam a localizar exposição excessiva.'},
{topic:'Restricted access',q:'What is true about SharePoint restricted access control?',o:['It replaces all site permissions','It limits site access to specified groups but does not grant access by itself','It only controls Copilot licenses','It deletes anonymous links automatically'],c:1,n:'O controle cria um limite adicional; a permissão normal ainda é necessária.'}
];
vocabGrid.innerHTML=VOCAB.map(([en,pt])=>`<article><strong>${en}</strong><span>${pt}</span></article>`).join('');let index=0,score=0,locked=false;
function render(){const x=Q[index];locked=false;examProgress.textContent=`Question ${index+1} of ${Q.length}`;examScore.textContent=`Score: ${score}`;nextQuestion.hidden=true;examCard.innerHTML=`<article class="exam-card"><span class="exam-card__topic">${x.topic}</span><h2>${x.q}</h2><div class="exam-options">${x.o.map((o,i)=>`<button data-o="${i}"><b>${String.fromCharCode(65+i)}</b>${o}</button>`).join('')}</div><div id="explain" class="exam-explain" hidden></div></article>`;examCard.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>answer(b,x)))}
function answer(btn,x){if(locked)return;locked=true;const ok=+btn.dataset.o===x.c;if(ok)score++;examCard.querySelectorAll('button').forEach((b,i)=>{b.disabled=true;if(i===x.c)b.classList.add('correct');else if(b===btn)b.classList.add('wrong')});explain.hidden=false;explain.innerHTML=`<strong>${ok?'Correct!':'Review this point.'}</strong><p>${x.n}</p>`;examScore.textContent=`Score: ${score}`;nextQuestion.textContent=index===Q.length-1?'See final result →':'Next question →';nextQuestion.hidden=false}
nextQuestion.addEventListener('click',()=>{index++;index<Q.length?render():finish()});function finish(){examCard.hidden=true;nextQuestion.hidden=true;examResult.hidden=false;finalScore.textContent=`${score}/10`;finalMessage.textContent=score>=8?'Excellent. Your data governance map is ready for the exam.':'Review the Portuguese notes and challenge the guardians again.'}restartExam.addEventListener('click',()=>{index=0;score=0;examCard.hidden=false;examResult.hidden=true;render()});render();
