const VOCAB=[['agent','agente'],['custom agent','agente personalizado'],['Researcher','Pesquisador'],['Analyst','Analista'],['monthly license','licença mensal'],['pay-as-you-go','pagamento conforme o uso'],['billing policy','política de cobrança'],['license assignment','atribuição de licença'],['adoption','adoção'],['usage report','relatório de uso'],['Copilot Analytics','Análise do Copilot'],['saved prompt','prompt salvo'],['scheduled prompt','prompt agendado'],['approval process','processo de aprovação'],['operational insights','insights operacionais'],['agent lifecycle','ciclo de vida do agente']];
const Q=[
{topic:'Capabilities',q:'Which capability is best suited to conduct complex research and synthesize information from multiple sources?',o:['Analyst','Researcher','A billing policy','A retention label'],c:1,n:'Researcher é indicado para pesquisa aprofundada e síntese de fontes.'},
{topic:'Capabilities',q:'A user needs help reasoning over data and identifying patterns. Which capability should be selected?',o:['Researcher','SharePoint Advanced Management','Analyst','Communication Compliance'],c:2,n:'Analyst é o especialista para raciocínio e análise de dados.'},
{topic:'Licensing',q:'Which model charges for metered consumption instead of assigning a fixed monthly Copilot license to each user?',o:['Pay-as-you-go','Monthly licensing','Sensitivity labeling','Single sign-on'],c:0,n:'Pay-as-you-go usa consumo medido associado a uma política de cobrança.'},
{topic:'Administration',q:'What should an administrator do to make licensed Copilot capabilities available to a specific user?',o:['Create an eDiscovery case','Assign the appropriate Copilot license','Create a sensitivity label','Enable anonymous sharing'],c:1,n:'A atribuição da licença habilita a capacidade licenciada para o usuário elegível.'},
{topic:'Adoption',q:'Which combination helps an administrator monitor Copilot usage and adoption?',o:['Exchange message trace and eDiscovery','Microsoft 365 admin center and Copilot Analytics','Entra sign-in logs only','DLP alerts and retention'],c:1,n:'O centro de administração do Microsoft 365 e Copilot Analytics fornecem sinais de uso e adoção.'},
{topic:'Prompts',q:'A reusable prompt must run at a future recurring time. Which prompt action is required?',o:['Delete','Share only','Schedule','Label'],c:2,n:'Prompts podem ser agendados, além de salvos, compartilhados e excluídos.'},
{topic:'Agent access',q:'An agent must be available only to members of a department. What should be configured?',o:['User or group access to the agent','A global anonymous link','A distribution group mailbox','A retention period'],c:0,n:'O acesso ao agente deve ser direcionado aos usuários ou grupos apropriados.'},
{topic:'Agent governance',q:'What is the primary purpose of an agent approval process?',o:['To grant every user access to all data','To review an agent before broader availability','To replace testing','To purchase licenses automatically'],c:1,n:'A aprovação cria um portão de governança antes da disponibilização mais ampla.'},
{topic:'Monitoring',q:'Which admin center is associated with environment and operational insights for agents built on Power Platform capabilities?',o:['Exchange admin center','SharePoint admin center','Microsoft Purview portal','Power Platform admin center'],c:3,n:'O Power Platform admin center ajuda a acompanhar ambientes e operação relacionada.'},
{topic:'Lifecycle',q:'An agent has no owner, no usage, and outdated knowledge. What is the best administrative response?',o:['Give it Global Administrator','Review and retire it through the lifecycle process','Publish it to everyone','Disable all Copilot features'],c:1,n:'Revisão e aposentadoria controlada evitam agentes órfãos e obsoletos.'}
];
vocabGrid.innerHTML=VOCAB.map(([en,pt])=>`<article><strong>${en}</strong><span>${pt}</span></article>`).join('');let index=0,score=0,locked=false;function render(){const x=Q[index];locked=false;examProgress.textContent=`Question ${index+1} of 10`;examScore.textContent=`Score: ${score}`;nextQuestion.hidden=true;examCard.innerHTML=`<article class="exam-card"><span class="exam-card__topic">${x.topic}</span><h2>${x.q}</h2><div class="exam-options">${x.o.map((o,i)=>`<button data-o="${i}"><b>${String.fromCharCode(65+i)}</b>${o}</button>`).join('')}</div><div id="explain" class="exam-explain" hidden></div></article>`;examCard.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>answer(b,x)))}function answer(btn,x){if(locked)return;locked=true;const ok=+btn.dataset.o===x.c;if(ok)score++;examCard.querySelectorAll('button').forEach((b,i)=>{b.disabled=true;if(i===x.c)b.classList.add('correct');else if(b===btn)b.classList.add('wrong')});explain.hidden=false;explain.innerHTML=`<strong>${ok?'Correct!':'Review this point.'}</strong><p>${x.n}</p>`;examScore.textContent=`Score: ${score}`;nextQuestion.textContent=index===9?'See final result →':'Next question →';nextQuestion.hidden=false}nextQuestion.addEventListener('click',()=>{index++;index<10?render():finish()});function finish(){examCard.hidden=true;nextQuestion.hidden=true;examResult.hidden=false;finalScore.textContent=`${score}/10`;finalMessage.textContent=score>=8?'Excellent. You earned the Agent Master badge.':'Review the Portuguese notes and challenge the academy again.'}restartExam.addEventListener('click',()=>{index=0;score=0;examCard.hidden=false;examResult.hidden=true;render()});render();
