/* SC-900 · Módulo 4 — progresso e revisão */
const MODULE_KEY='sc900_module4_progress_v1';
const lessons=['aula-1','aula-2','aula-3','aula-4','aula-5','aula-6'];
let lessonState=loadModuleState();
function loadModuleState(){try{return JSON.parse(localStorage.getItem(MODULE_KEY)||'{}')}catch{return{}}}
function saveModuleState(){try{localStorage.setItem(MODULE_KEY,JSON.stringify(lessonState))}catch{}}
function showToast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function updatePathDots(){document.querySelectorAll('.path-dot[data-lesson]').forEach(dot=>dot.classList.toggle('completed',!!lessonState[`aula-${dot.dataset.lesson}`]))}
function updateModuleProgress(){const done=lessons.filter(id=>lessonState[id]).length,pct=Math.round(done/lessons.length*100);document.getElementById('moduleProgress').textContent=`${pct}%`;document.getElementById('moduleFill').style.width=`${pct}%`;document.getElementById('moduleHint').textContent=pct===0?'Leia cada aula e marque como concluída 👇':pct<100?`${done} de ${lessons.length} aulas concluídas — continue! 💪`:'🎉 Módulo completo! Bora pro quiz?';updatePathDots()}
document.querySelectorAll('.lesson__done').forEach(btn=>{const id=btn.dataset.complete;const paint=()=>{btn.classList.toggle('completed',!!lessonState[id]);btn.innerHTML=lessonState[id]?'<span class="lesson__done-check">✓</span> Aula concluída! ✓':'<span class="lesson__done-check">✓</span> Marcar aula como concluída'};paint();btn.addEventListener('click',()=>{lessonState[id]=!lessonState[id];if(!lessonState[id])delete lessonState[id];saveModuleState();paint();updateModuleProgress();showToast(lessonState[id]?'✅ Aula concluída!':'Aula reaberta.')})});updateModuleProgress();

const QUESTIONS=[
{q:'Onde um auditor encontra relatórios de auditoria e documentos de conformidade dos serviços Microsoft?',o:['Compliance Manager','Service Trust Portal','Activity explorer','eDiscovery'],c:1,e:'O <strong>Service Trust Portal</strong> disponibiliza relatórios, certificações e documentação de confiança.'},
{q:'O compliance score do Compliance Manager prova automaticamente que a empresa está legalmente conforme?',o:['Sim, sempre','Não; ele mede ações e ajuda a priorizar, mas não substitui avaliação jurídica','Sim, quando chega a 70%','Somente em SaaS'],c:1,e:'O score é uma medida de progresso baseada em controles e ações, <strong>não uma garantia ou certificação legal</strong>.'},
{q:'Qual recurso responde melhor à pergunta “onde estão os itens com determinado sensitivity label”?',o:['Activity explorer','Content explorer','Audit','Insider Risk Management'],c:1,e:'<strong>Content explorer</strong> mostra conteúdo e locais; Activity explorer mostra atividades realizadas.'},
{q:'Qual solução pode aplicar criptografia e marca d’água persistentes a um documento?',o:['Sensitivity label','Retention policy','Compliance score','Audit'],c:0,e:'Um <strong>sensitivity label</strong> classifica e pode aplicar proteção persistente, incluindo criptografia e marcas visuais.'},
{q:'Qual é a principal diferença entre DLP e retenção?',o:['DLP controla vazamento/uso; retenção governa quanto tempo manter ou excluir','DLP é apenas para email; retenção apenas para Teams','São exatamente o mesmo recurso','Retenção bloqueia phishing; DLP cria backups'],c:0,e:'<strong>DLP</strong> controla uso e compartilhamento de dados sensíveis; <strong>retenção</strong> controla ciclo de vida.'},
{q:'Uma equipe jurídica precisa preservar e pesquisar emails relacionados a um processo. Qual solução usar?',o:['Insider Risk Management','eDiscovery','Compliance Manager','Content explorer'],c:1,e:'<strong>eDiscovery</strong> permite criar casos, preservar, pesquisar, revisar e exportar conteúdo relevante.'}
];
const quizContainer=document.getElementById('quizContainer'),quizResult=document.getElementById('quizResult');let answers=[];
function renderQuiz(){answers=[];quizResult.hidden=true;quizContainer.innerHTML=QUESTIONS.map((x,q)=>`<div class="quiz-q"><div class="quiz-q__num">Pergunta ${q+1} de ${QUESTIONS.length}</div><div class="quiz-q__text">${x.q}</div><div class="quiz-options">${x.o.map((o,i)=>`<button class="quiz-opt" data-q="${q}" data-o="${i}"><span class="quiz-opt__letter">${String.fromCharCode(65+i)}</span><span>${o}</span></button>`).join('')}</div></div>`).join('');quizContainer.querySelectorAll('.quiz-opt').forEach(b=>b.addEventListener('click',handleAnswer))}
function handleAnswer(e){const b=e.currentTarget,q=+b.dataset.q,o=+b.dataset.o;if(answers[q]!==undefined)return;answers[q]=o===QUESTIONS[q].c;const block=b.closest('.quiz-q');block.querySelectorAll('.quiz-opt').forEach(x=>{x.classList.add('disabled');if(+x.dataset.o===QUESTIONS[q].c)x.classList.add('correct');if(x===b&&o!==QUESTIONS[q].c)x.classList.add('wrong')});block.insertAdjacentHTML('beforeend',`<div class="quiz-q__explain"><strong>${answers[q]?'✅ Correto!':'❌ Quase!'}</strong> ${QUESTIONS[q].e}</div>`);if(answers.filter(x=>x!==undefined).length===QUESTIONS.length)setTimeout(showResult,400)}
function showResult(){const score=answers.filter(Boolean).length;document.getElementById('quizScore').textContent=`${score}/${QUESTIONS.length}`;document.getElementById('quizMsg').textContent=score>=5?'🎉 Ótimo! Agora encare o English Exam Mode.':'📖 Reveja as diferenças entre classificação, proteção, retenção e investigação.';quizResult.hidden=false;quizResult.scrollIntoView({behavior:'smooth',block:'center'})}
document.getElementById('quizRetry').addEventListener('click',renderQuiz);renderQuiz();
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
